on: [push, pull_request]
name: pylinter-odoo
author: José Angel Inda Herrera
description: Lint odoo python projects with flake8 pylint-odoo. The build will fail on violations.
branding:
  color: 'gray-dark'
  icon: 'check-circle'

inputs:
  python-root:
    description: 'directory to run linting on'
    required: false
    default: '.'  
  flake8-flags:
    description: 'flake8 flags'
    required: false
    default: '--ignore=F401 --max-line-length=80'
  skip-flake8:
    description: 'skip flake8 checks'
    required: false
    default: false
  skip-black:
    description: 'skip-black'
    required: false
    default: ''
runs:
  using: 'docker'
  image: docker://jainda/odoo-actions
  args:
    - ${{ inputs.python-root }}
    - ${{ inputs.flake8-flags }}
    - ${{ inputs.skip-flake8 }}
    - ${{ inputs.skip-black }}